In [17]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [18]:
df = pd.read_csv('train.txt',sep = ';',header = None,names=['text','emotions'])

In [19]:
df

                                                    text emotions
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [20]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [21]:
unique_emotions = df['emotions'].unique()
emotion_num = {}
i = 0
for emo in unique_emotions:
    emotion_num[emo] = i
    i += 1

df['emotions'] = df['emotions'].map(emotion_num)

In [22]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [23]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [24]:
# punctuations removing

import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [25]:
df['text'] = df['text'].apply(remove_punc)

In [26]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [27]:
# remove numbers

def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [28]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [29]:
# remove emojis

def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [30]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [31]:
import nltk

In [32]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [33]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /Users/yogesh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/yogesh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [34]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/yogesh/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [35]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [36]:
stop_words = set(stopwords.words('english'))

In [37]:
# removing stopwords

def remove(txt):
    words = txt.split()
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

In [38]:
df['text'] = df['text'].apply(remove)

In [39]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(df['text'],df['emotions'], test_size=0.20, random_state=42)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [43]:
bow_vectorizer = CountVectorizer()

In [44]:
x_train_bow = bow_vectorizer.fit_transform(X_train)
x_test_bow = bow_vectorizer.transform(X_test)

In [45]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [46]:
nb_model = MultinomialNB()

In [47]:
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [48]:
pred_nb = nb_model.predict(x_test_bow)

In [49]:
print(accuracy_score(y_test,pred_nb))

0.768125

In [50]:
tfidf_vectorizer = TfidfVectorizer()

In [51]:
x_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf = tfidf_vectorizer.transform(X_test)

In [52]:
nb2_model = MultinomialNB()

In [53]:
nb_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [54]:
pred_nb1 = nb_model.predict(x_test_tfidf)

In [55]:
print(accuracy_score(y_test,pred_nb1))

0.6609375

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
logistic_model = LogisticRegression()

In [58]:
logistic_model.fit(x_train_tfidf,y_train)

LogisticRegression()

In [59]:
log_pred = logistic_model.predict(x_test_tfidf)

In [60]:
print(accuracy_score(y_test,log_pred))

0.8628125

In [61]:
import joblib

In [62]:
joblib.dump(logistic_model,'sentimental_analysis.pkl')
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.pkl')
print("Model and Vectorizer saved successfully!")

Model and Vectorizer saved successfully!